batch_size: 16
batch_size_valid: 8
epochs: 120
lr: 7.5e-05
weight_decay: 0.00015
rand_seed: 42
precisionHigh: true
train_dir: /root/data-tmp/COD/Train
test_dir: /root/data-tmp/COD/Test/NC4K
load_all: false
backbone: pvt_v2_b5
img_size: 416
lateral_channels:
- 512
- 320
- 128
- 64
resume: ''
compile: false
device_ids:
- 0
multi_GPU: false
save_model_dir: /root/data-tmp/workspace/02_experiments/runs
name: baseline_escnet_b5_clean_eval
save_last: 30
save_step: 3
preproc_methods:
- flip
- rotate
- pepper
- crop
weights:
  pvt_v2_b2: /root/data-tmp/weights/pvt_v2_b2.pth
  pvt_v2_b4: /root/data-tmp/weights/pvt_v2_b2.pth
  pvt_v2_b5: /root/data-tmp/weights/pvt_v2_b5_22k.pth
num_workers: 4
